const types = {
  GET_USERS_START: 'GET_USERS_START',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_ERROR: 'GET_USERS_ERROR',
  GET_STARTS_START: 'GET_STARTS_START',
  GET_STARTS_SUCCESS: 'GET_STARTS_SUCCESS',
  GET_STARTS_ERROR: 'GET_STARTS_ERROR',
};

export default types;
